# Generated by Django 5.2.6 on 2025-10-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_links_student_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='links',
        ),
    ]
