# Generated by Django 5.2.6 on 2025-10-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.links'),
        ),
    ]
