# Generated by Django 5.2.6 on 2025-10-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='links',
        ),
        migrations.AddField(
            model_name='links',
            name='links',
            field=models.ManyToManyField(null=True, related_name='links', to='accounts.student'),
        ),
    ]
