# Generated by Django 5.2.6 on 2025-10-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_student_links_links_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='links',
        ),
        migrations.AddField(
            model_name='links',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='links', to='accounts.student'),
        ),
    ]
