# Generated by Django 5.2.6 on 2025-10-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_course_created_at_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.chapter'),
        ),
    ]
